### ISSUE TITLE
Update 2.2.0 Marketplace HTTP 500

### ISSUE THREAD

**Issue by TARSISP** [ticgal/yagp#35]
AFTER THE LAST UPDATE OF THE PLUG-IN, IT DOESN'T INSTALL, AN ERROR MESSAGE APPEARS ON THIS LINK https://angedesk.angeloni.com.br/front/plugin.form.php  
This page is not workingangedesk.glpi.com.br is unable to fulfill this request at this time.
HTTP ERROR 500

**Comment by OscarBeiro** [comment]
A 500 error typically is related to your webserver, no the plugin.
Please review your Apache logs and fix them.
Regards,

**Comment by dxdemetriou** [comment]
> A 500 error typically is related to your webserver, no the plugin. Please review your Apache logs and fix them. Regards,

The problem appeared after the update from 2.1.1 to 2.2.0. In my case I removed the addon from marketplace and returned to 2.1.1 into plugins directory. There is no any specific error into Apache logs, just the 500 error, no idea what other to check. The php is 7.4 (the default on CentOS 8 based if it's the reason)

**Comment by dxdemetriou** [comment]
This is from php-fpm:
````
[04-Dec-2023 14:03:30 Asia/Nicosia] PHP Notice:  Undefined index: date in /var/www/html/glpi/plugins/yagp/inc/ticket.class.php on line 128
[04-Dec-2023 17:56:46 Asia/Nicosia] PHP Warning:  Unable to load plugin "yagp" information. in /var/www/html/glpi/src/Plugin.php on line 621
[04-Dec-2023 17:56:52 Asia/Nicosia] PHP Warning:  Plugin "yagp" version changed. It has been deactivated as its update process has to be launched. in /var/www/html/glpi/src/Plugin.php on line 657
[04-Dec-2023 17:57:11 Asia/Nicosia] PHP Fatal error:  Constructor PluginYagpPostshowitem::pluginYagpPostShowItem() cannot be static in /var/www/html/glpi/plugins/yagp/inc/postshowitem.class.php on line 36

````

**Comment by OscarBeiro** [comment]
Hi, 
It could be PHP.
https://www.php.net/supported-versions.php
It's been a year since it is not supported, so we either don't.

Upgrading your PHP to 8.2, it's your safest bet.

**Comment by dxdemetriou** [comment]
> Hi, 
> It could be PHP.
> https://www.php.net/supported-versions.php
> It's been a year since it is not supported, so we either don't.
> 
> Upgrading your PHP to 8.2, it's your safest bet.

Right, but some servers using lts releases for example on RHEL 8 the 7.4 is supported until 2029 so many people will be affected (in this case 4 years after RHEL8 release).

https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle

On GLPI 10 the minimum PHP version is 7.4.

**Comment by OscarBeiro** [comment]
Well, they can pay for the support as they do for Redhat :)

For Open Source aligned versions, we stick to the official Roadmap, since we don't have the resources to support every possible setup.
https://www.php.net/supported-versions.php

You can propose a PR, sponsor a feature, or test it on a new server. If they fail on a higher PHP version we may give it a look.
We use this plugin on several GLPI servers without a problem.

Regards,

**Comment by willysaurio** [comment]
> > A 500 error typically is related to your webserver, no the plugin. Please review your Apache logs and fix them. Regards,
> 
> The problem appeared after the update from 2.1.1 to 2.2.0. In my case I removed the addon from marketplace and returned to 2.1.1 into plugins directory. There is no any specific error into Apache logs, just the 500 error, no idea what other to check. The php is 7.4 (the default on CentOS 8 based if it's the reason)

**I have the same problem. I have GLPI 10.0.5 installed and when I move YAGP from version 2.1.1 to 2.2.0 or 2.2.1 the plugin does not install. The solution I found is to download version 2.1.1 again and reinstall it ignoring the new versions of YAGP**
