### ISSUE TITLE
Multiple PHP warnings and non-working drop-downs

### ISSUE THREAD

**Issue by raregtp** [ticgal/yagp#37]
Using GLPI 10.0.10, and YAGP 2.2.0.

Getting this error flashing up on login and in various other screens:

![image](https://github.com/ticgal/yagp/assets/16689744/71d4efdf-6636-4593-8290-e9a43f83c955)

In addition, I have discovered these three options will not let me set them to 'Yes'....but I believe this to be related to the above error:

![image](https://github.com/ticgal/yagp/assets/16689744/5d1bbabf-616d-49d1-bbca-477a892d464d)

Please let me know if you need any other information.  Thanks!!

**Comment by OscarBeiro** [comment]
It looks like the issue is on the webresources plugin, which unfortunately I don't know.
Not sure if we need to do something about it.

**Comment by raregtp** [comment]
So your saying the above warnings and the non-working drop-downs are due to the Webresources plugin?  I did disable and uninstall that plugin but there is no change to the issue after doing so.  Am I missing something?

**Comment by OscarBeiro** [comment]
Sorry, I think I've mixed up some different Issues.
Could you please recreate it on a clean instance?

**Comment by raregtp** [comment]
Well......time-wise, I can't quickly test it on a clean instance.  That said, I have another instance in a test environment that is still on GLPI 10.0.8, and the latest version of YAGP does seem to work ok there (the drop-downs, not sure on the PHP warnings as I don't always see those on our prod instance).

I'm going to upgrade the 10.0.8 instance to 10.0.10 and see if there is any difference.  More to come.

**Comment by raregtp** [comment]
Ok....YAGP continued to work normally on the test system after upgrading to 10.0.10.  Embarrassingly, after looking at the plugin settings on the prod system we hadn't yet configured anything to "yes".....so I uninstalled and reinstalled the plugin and all is well.  Not sure what happened there but all is good...appreciate the dialog!

**Comment by OscarBeiro** [comment]
Good to know it is fixed :)
Thanks for the swift feedback.
